@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"D:\Program Files\IAR Systems\Embedded Workbench 6.0\common\bin\cspybat" "D:\Program Files\IAR Systems\Embedded Workbench 6.0\arm\bin\armproc.dll" "D:\Program Files\IAR Systems\Embedded Workbench 6.0\arm\bin\armrdi.dll"  %1 --plugin "D:\Program Files\IAR Systems\Embedded Workbench 6.0\arm\bin\armbat.dll" --macro "D:\Gpay01\Gpay010511\Common\SAM7SE512\Resource\SAM7_FLASH.mac" --backend -B "--endian=little" "--cpu=ARM7TDMI" "--fpu=None" "-p" "D:\Program Files\IAR Systems\Embedded Workbench 6.0\arm\CONFIG\debugger\Atmel\ioAT91SAM7SE512.ddf" "--semihosting" "--device=AT91SAM7SE512" "--rdi_driver_dll=d:\Program Files\SEGGER\JLinkARM_V390a\JLinkRDI.dll" "--drv_catch_exceptions=0x000" 


